<?php
	define( 'TWITTER_CONSUMER_KEY', 'YOUR-CONSUMER-KEY' );
	define( 'TWITTER_CONSUMER_SECRET', 'YOUR-CONSUMER-SECRET' );
	define( 'TWITTER_ACCESS_TOKEN', 'YOUR-ACCESS-TOKEN' );
	define( 'TWITTER_ACCESS_TOKEN_SECRET', 'YOUR-ACCESS-TOKEN-SECRET' );