<?php
	define( 'IG_CLIENT_ID', 'YOUR_IG_CLIENT_ID' );
	define( 'IG_CLIENT_SECRET', 'YOUR_IG_CLIENT_SECRET' );
	define( 'IG_REDIRECT_URI', 'YOUR_IG_REDIRECT_URI' );
	define( 'IG_ACCESS_TOKEN', 'YOUR_IG_ACCESS_TOKEN' );